--- # Notification and Handling events
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: install nginx web server
    yum:
      name: nginx
      state: latest
    notify: 
    - enable and restart nginx
  handlers:
  - name: enable and restart nginx
    service:
      name: nginx
      enabled: yes
      state: restarted
